<?php

namespace Reader\Bundle\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
    public function count()
    {
        $qb    = $this->createQueryBuilder()
            ->hydrate(false);
        $query = $qb->getQuery();
        $count = $query->execute()->count();
        return $count;
    }
}