reader_admin_dashboard:
    pattern:  /
    defaults: { _controller: ReaderAdminBundle:Default:dashboard }

reader_admin_login:
    pattern:  /login
    defaults: { _controller: ReaderAdminBundle:Default:login }

reader_admin_login_check:
    pattern:  /login_check
    defaults: { _controller: ReaderAdminBundle:Default:securityCheck }

reader_admin_logout:
    pattern:  /logout
    defaults: { _controller: ReaderAdminBundle:Default:logout }

reader_admin_site:
    pattern:  /site
    defaults: { _controller: ReaderAdminBundle:Site:index }

reader_admin_site_add:
    pattern:  /site/add
    defaults: { _controller: ReaderAdminBundle:Site:add }

reader_admin_category_add:
    pattern:  /category/add
    defaults: { _controller: ReaderAdminBundle:Category:add }

reader_admin_site_update:
    pattern:  /site/update/{id}
    defaults: { _controller: ReaderAdminBundle:Site:update }

reader_admin_category_update:
    pattern:  /category/update/{id}
    defaults: { _controller: ReaderAdminBundle:Category:update }