reader_admin_dashboard:
    pattern:  /
    defaults: { _controller: ReaderAdminBundle:Default:dashboard }

reader_admin_random_stories:
    pattern:  /random_stories/{limit}
    defaults: { _controller: ReaderAdminBundle:Default:storiesRandom }

reader_admin_login:
    pattern:  /login
    defaults: { _controller: ReaderAdminBundle:Default:login }

reader_admin_login_check:
    pattern:  /login_check
    defaults: { _controller: ReaderAdminBundle:Default:securityCheck }

reader_admin_logout:
    pattern:  /logout
    defaults: { _controller: ReaderAdminBundle:Default:logout }

reader_admin_site:
    pattern:  /site
    defaults: { _controller: ReaderAdminBundle:Site:index }

reader_admin_site_add:
    pattern:  /site/add
    defaults: { _controller: ReaderAdminBundle:Site:add }

reader_admin_category_add:
    pattern:  /category/add
    defaults: { _controller: ReaderAdminBundle:Category:add }

reader_admin_site_update:
    pattern:  /site/update/{id}
    defaults: { _controller: ReaderAdminBundle:Site:update }

reader_admin_site_delete:
    pattern:  /site/delete/{id}
    defaults: { _controller: ReaderAdminBundle:Site:delete }

reader_admin_category_update:
    pattern:  /category/update/{id}
    defaults: { _controller: ReaderAdminBundle:Category:update }

reader_admin_category_delete:
    pattern:  /category/delete/{id}
    defaults: { _controller: ReaderAdminBundle:Category:delete }

reader_admin_site_view:
    pattern:  /site/view/{id}
    defaults: { _controller: ReaderAdminBundle:Site:view }

reader_admin_site_grab:
    pattern:  /site/grab/{id}/{page}
    defaults: { _controller: ReaderAdminBundle:Site:grab }

reader_admin_site_stories:
    pattern:  /site/stories/{id}/{page}/{returnCount}/{limit}
    defaults: { _controller: ReaderAdminBundle:Site:stories }

reader_admin_site_stories_random:
    pattern:  /site/stories/random/{id}/{limit}
    defaults: { _controller: ReaderAdminBundle:Site:storiesRandom }

reader_admin_site_purge:
    pattern:  /site/purge/{id}
    defaults: { _controller: ReaderAdminBundle:Site:purgeStories }

reader_admin_site_sandbox:
    pattern:  /site/sandbox/{id}
    defaults: { _controller: ReaderAdminBundle:Site:sandbox }

reader_admin_site_iframe:
    pattern:  /site/iframe/{id}/{page}
    defaults: { _controller: ReaderAdminBundle:Site:iframe }

reader_admin_story_delete:
    pattern:  /story/delete/{id}
    defaults: { _controller: ReaderAdminBundle:Story:delete }

reader_admin_user:
    pattern:  /user
    defaults: { _controller: ReaderAdminBundle:User:index }

reader_admin_user_add:
    pattern:  /user/add
    defaults: { _controller: ReaderAdminBundle:User:add }

reader_admin_user_update:
    pattern:  /user/update/{id}
    defaults: { _controller: ReaderAdminBundle:User:update }

reader_admin_user_delete:
    pattern:  /user/delete/{id}
    defaults: { _controller: ReaderAdminBundle:User:delete }

reader_admin_user_view:
    pattern:  /user/view/{id}
    defaults: { _controller: ReaderAdminBundle:User:view }

reader_admin_user_list:
    pattern:  /user/list/{page}/{limit}
    defaults: { _controller: ReaderAdminBundle:User:list }

reader_admin_test:
    pattern:  /test
    defaults: { _controller: ReaderAdminBundle:Default:test }

reader_admin_search:
    pattern:  /search
    defaults: { _controller: ReaderAdminBundle:Search:simple }

reader_admin_sandbox:
    pattern:  /sandbox
    defaults: { _controller: ReaderAdminBundle:Default:sandbox }

reader_admin_iframe:
    pattern:  /iframe/{frameUrl}
    defaults: { _controller: ReaderAdminBundle:Default:iframe }
    requirements:
        frameUrl: .+