parameters:
    reader_user.oauth_provider.class: Reader\Bundle\UserBundle\Auth\OAuthProvider

services:
    reader_user.oauth_provider:
        class: %reader_user.oauth_provider.class%
        arguments: [@service_container, @doctrine_mongodb.odm.document_manager]
