Reader\Bundle\UserBundle\Document\User:
    repositoryClass: Reader\Bundle\UserBundle\Repository\UserRepository
    fields:
        id:
            id: true
        email:
            type: string
        password:
            type: string
        created:
            type: timestamp
        roles:
            type: collection
    lifecycleCallbacks: {}