reader_user:
    resource: "@ReaderUserBundle/Resources/config/routing.yml"
    prefix:   /

reader_grabber:
    resource: "@ReaderGrabberBundle/Resources/config/routing.yml"
    prefix:   /

reader_design:
    resource: "@ReaderDesignBundle/Resources/config/routing.yml"
    prefix:   /

reader:
    resource: "@ReaderBundle/Resources/config/routing.yml"
    host:     '%public_host%'
    prefix:   /

reader_admin:
    resource: "@ReaderAdminBundle/Resources/config/routing.yml"
    host:     '%admin_host%'
    prefix:   /

