security:
    encoders:
        Reader\Bundle\UserBundle\Document\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        reader_users:
            mongodb: { class: ReaderUserBundle:User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:    ^/admin
            #request_matcher: reader_admin.firewall.request_matcher
            anonymous: ~
            provider: reader_users
            form_login:
                check_path: reader_admin_login_check
                login_path: reader_admin_login
                default_target_path: reader_admin_dashboard
            logout:
                path:   reader_admin_logout
                target: /admin

        front:
            pattern:    ^/
            anonymous: ~
            logout: true
            logout:
                path:   reader_front_logout
                target: reader_front_homepage
            oauth:
                resource_owners:
                    google:            google_login
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: reader_user.oauth_provider
            #provider: reader_users
            #form_login:
            #    check_path: reader_front_login_check
            #    login_path: reader_front_login
            #logout:
            #    path:   reader_front_logout
            #    target: /

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
