security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        admin:
            pattern:    ^/
            request_matcher: reader_admin.firewall.request_matcher
            anonymous: ~
            provider: in_memory
            form_login:
                check_path: reader_admin_login_check
                login_path: reader_admin_login
            logout:
                path:   reader_admin_logout
                target: /

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %admin_host% }
        - { path: ^/, roles: ROLE_ADMIN, host: %admin_host% }
