<?php

namespace Reader\Bundle\ReaderBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * StoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryRepository extends DocumentRepository
{
}