Reader\Bundle\ReaderBundle\Document\Site:
    repositoryClass: Reader\Bundle\ReaderBundle\Repository\SiteRepository
    fields:
        id:
            id:  true
        identifier:
            type: string
        title:
            type: string
        shortTitle:
            type: string
        url:
            type: string
        urlPattern:
            type: string
        urlFirstPage:
            type: int
        urlStep:
            type: int
        grabSelector:
            type: string
        allowedTags:
            type: string
        imageTag:
            type: string
        featured:
            type: boolean
        logoPath:
            type: string
    referenceMany:
        categories:
            targetDocument: Reader\Bundle\ReaderBundle\Document\Category
            sort: { identifier: asc }
            nullable: true
    lifecycleCallbacks:
        preRemove: [ storeFilenameForRemove ]
        postRemove: [ removeUpload ]
        prePersist: [ preUpload, upload ]
        preUpdate: [ preUpload, upload ]