Reader\Bundle\ReaderBundle\Document\Story:
    repositoryClass: Reader\Bundle\ReaderBundle\Repository\StoryRepository
    fields:
        id:
            id:  true
        text:
            type: string
        title:
            type: string
        textSum:
            type: string
        grabbed:
            type: timestamp
        page:
            type: int
        position:
            type: int
        image:
            type: string
        randomizer:
            type: collection
    indexes:
        random:
            keys:
                randomizer: 2d
    referenceOne:
        site:
            targetDocument: Reader\Bundle\ReaderBundle\Document\Site
            nullable: false
#    embedOne:
#        randomizer:
#            targetDocument: Reader\Bundle\ReaderBundle\Document\Randomizer
#            nullable: false
    lifecycleCallbacks:
        preRemove: [ storeFilenameForRemove ]
        postRemove: [ removeUpload ]