parameters:
#    reader.example.class: Reader\Bundle\ReaderBundle\Example

services:
#    reader.example:
#        class: %reader.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
